# Generated by Django 5.0.7 on 2024-09-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShowMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('show_date_and_time', models.DateTimeField()),
                ('available_seats', models.IntegerField(default=80)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.halls')),
            ],
        ),
    ]
