# Generated by Django 5.0.7 on 2024-09-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_halls_showmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showmovies',
            old_name='hall_id',
            new_name='hall',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.showmovies')),
            ],
        ),
    ]
